<div class="alert alert-info">
    <h1>Examples of algorithms</h1>
</div>

<table class="table table-striped table-hover">
    <tr>
        <th>Algorithm</th>
        <th>Url</th>
    </tr>
    <tr>
        <td>Sort</td>
        <td>
            <a href="<?= $this->url('algorithm/sort', ['action' => 'index',], ['query' => ['fr' => 'zend']]); ?>">
            sort
            </a>
        </td>
    </tr>
</table>